plugins {
    id 'com.android.application'
}

android {
    namespace 'ai.ibrahim.nativeapp'
    compileSdk 35

    defaultConfig {
        applicationId 'ai.noxara.ibrahim.v24'
        minSdk 26
        targetSdk 35
        versionCode 29
        versionName '29.0-voice-room'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'ai.picovoice:porcupine-android:4.0.2'
}
